env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = WLR_NO_HARDWARE_CURSORS,1

#chatgpt conf
#suomalainen nappis
input {
	kb_layout = fi
}

$mod = SUPER

exec-once = waybar
exec-once = dunst

bind = $mod, RETURN, exec, alacritty
bind = $mod, D, exec, rofi -show drun
bind = $mod, Q, killactive

bind = $mod, M, exit

#moi
