




wallpaper {
    monitor = DP-2
    path = /home/paha/Kuvat/wallhaven-dpxowm.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-3
    path = /home/paha/Kuvat/wallhaven-dpxowm.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/paha/Kuvat/wallhaven-dpxowm.png
    fit_mode = cover
}
